name: maps_example_dart
description: Shared Dart code for the example apps.
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter_ios:
    git:
      url: https://github.com/danyialkhan/packages.git
      path: packages/google_maps_flutter/google_maps_flutter_ios
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/danyialkhan/packages.git
      path: packages/google_maps_flutter/google_maps_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  stream_transform: ^2.0.0

flutter:
  uses-material-design: true
